openapi: "3.1.0"
info:
  title: Example
  version: 1
paths:
  "/example":
    get:
      description: "Example endpoint"
      operationId: example
      summary: "Example endpoint"
      responses:
        "200":
          description: "Success"
          content:
            "application/json":
              schema:
                "$ref": "#/components/schemas/user"
components:
  schemas:
    user:
      type: object
      properties:
        id:
          type: integer
      required:
        - id
